### ISSUE TITLE
could not find function "generate_alpha_test_pair"

### ISSUE THREAD

**Issue by aea-adura** [cafferychen777/MicrobiomeStat-Turtorial-Professional-Version#2]

**Comment by cafferychen777** [comment]
Hi @Aristotle1992,
 
I've just checked and verified that the code is working correctly on my end. I was able to successfully run the example with the `generate_alpha_test_pair` function using the provided code. 

Could you please confirm:
1. Which version of MicrobiomeStat you're using
2. Whether you're getting any specific error messages when installing the package

This will help me better understand what might be causing the issue on your system.

Best regards,
Chen
